# Generated by Django 3.2.9 on 2021-11-30 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curie', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseFillToGeneResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('fill_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dis2g_fill_disease', to='chp_learn.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curie', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('fill_dis2g_results', models.ManyToManyField(related_name='dis2g_filled_by', through='chp_learn.DiseaseFillToGeneResult', to='chp_learn.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='GeneFillToGeneResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('fill_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g2g_fill_gene', to='chp_learn.gene')),
                ('query_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g2g_query_gene', to='chp_learn.gene')),
            ],
        ),
        migrations.CreateModel(
            name='GeneFillToDiseaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g2dis_fill_gene', to='chp_learn.gene')),
                ('query_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g2dis_query_disease', to='chp_learn.disease')),
            ],
        ),
        migrations.AddField(
            model_name='gene',
            name='fill_g2g_results',
            field=models.ManyToManyField(related_name='g2g_filled_by', through='chp_learn.GeneFillToGeneResult', to='chp_learn.Gene'),
        ),
        migrations.AddField(
            model_name='diseasefilltogeneresult',
            name='query_gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dis2g_query_gene', to='chp_learn.gene'),
        ),
        migrations.AddField(
            model_name='disease',
            name='fill_g2dis_results',
            field=models.ManyToManyField(related_name='g2dis_filled_by', through='chp_learn.GeneFillToDiseaseResult', to='chp_learn.Gene'),
        ),
    ]
