# Generated by Django 4.0.5 on 2022-06-25 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curie', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseToFillGeneResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('predicate', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curie', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('fill_dis2g_results', models.ManyToManyField(related_name='dis2g_filled_by', through='chp_learn.DiseaseToFillGeneResult', to='chp_learn.disease')),
            ],
        ),
        migrations.CreateModel(
            name='GeneToFillGeneResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('predicate', models.CharField(max_length=128)),
                ('fill_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g2g_fill_gene', to='chp_learn.gene')),
                ('query_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g2g_query_gene', to='chp_learn.gene')),
            ],
        ),
        migrations.CreateModel(
            name='GeneToFillDiseaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('fill_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dis2g_fill_disease', to='chp_learn.disease')),
                ('query_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dis2g_query_gene', to='chp_learn.gene')),
            ],
        ),
        migrations.AddField(
            model_name='gene',
            name='fill_g2g_results',
            field=models.ManyToManyField(related_name='g2g_filled_by', through='chp_learn.GeneToFillGeneResult', to='chp_learn.gene'),
        ),
        migrations.AddField(
            model_name='diseasetofillgeneresult',
            name='fill_gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g2dis_fill_gene', to='chp_learn.gene'),
        ),
        migrations.AddField(
            model_name='diseasetofillgeneresult',
            name='query_disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g2dis_query_disease', to='chp_learn.disease'),
        ),
        migrations.AddField(
            model_name='disease',
            name='fill_g2dis_results',
            field=models.ManyToManyField(related_name='g2dis_filled_by', through='chp_learn.GeneToFillDiseaseResult', to='chp_learn.gene'),
        ),
    ]
