# Generated by Django 3.2.9 on 2022-02-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chp_learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genefilltodiseaseresult',
            name='relation',
            field=models.CharField(default='NA', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genefilltodiseaseresult',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
