# Generated by Django 3.2.9 on 2022-02-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chp_learn', '0002_auto_20220216_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='genefilltogeneresult',
            name='relation',
            field=models.CharField(default='NA', max_length=128),
            preserve_default=False,
        ),
    ]
