# Generated by Django 3.2.9 on 2022-02-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chp_learn', '0003_genefilltogeneresult_relation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneFillToDiseaseResult',
            new_name='DiseaseToFillGeneResult',
        ),
        migrations.RenameModel(
            old_name='DiseaseFillToGeneResult',
            new_name='GeneToFillDiseaseResult',
        ),
        migrations.RenameModel(
            old_name='GeneFillToGeneResult',
            new_name='GeneToFillGeneResult',
        ),
    ]
